language:
- 'generic'
compiler:
- 'gcc'
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
addons:
  apt:
    update: true
    packages:
      - ghostscript
script:
  - 'make'
