language:
- generic
compiler:
- gcc
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends texlive-full
- sudo apt-get install ghostscript
script:
- make
deploy:
  provider: releases
  api_key:
    secure: GlhkK8IyHGyAvELfWpgyCRJcZS6rZeH8ramb2HHARu4fBJmTvbwRYjTe0YhNKVUV7U/aEQi0ArXTHyi41bVL5NXsv1rQKEIWpXAKrb2Bww3IIb8FDU9dfFeVRsw4Pe6RAWtvjVHfuxb5tgEnVAUfctrxUQD4JatQAYuVSpV0wrCCK4JoCZdviHxC8kBZUI89bEeTE/SRcbxdoeDzTutJobjooIKMgsM5ju5FrvrUwR6AW4410q0dXzD27Zmd5w5R63Ao92pPl4EzB2omo/zFc0627R1zv92pyDwH4rF2e7wkm09eO1JoYuSruQ2RR3Ix5FN1sbDxzihIS00g1Btcig3HnTNf10ZTkoNOGPSreFDwOQ0+nBnlMrrQWRPpNNT4BGHXMtYm2RwT6Xr7Rz2tDUeP7yNVPpM1lNarCmyJDq/svd7LrfE7AATPXb55QxCeHBcEhETsXaUkoqJEZZ2rUz3Chdfu4VGGGr9GlapdhxthHy/0LOGxANbWOd0mtEvoT5JKzy6pFX9F4whRQBHPUL9xdl61gSlljPd9RECLNyiAMFNWDTN704WTvTsOm+IZujxUtUfDCvM5PPeSVObdtd++RuCBy0v8zLc/PPv2cBP8ZLCby28VuAOU6DSQbqwQdVyji2aUnyQ20G4Mbl8e7FDAm8yQiYSu597HziRsMec=
  file:
  - build/studentbrad_coop_contribution.pdf
  - build/studentbrad_coop_nominee_bio.pdf
  - build/studentbrad_coop_personal_statement.pdf
  - build/studentbrad_personal_bio.pdf
  - build/studentbrad_personal_resume.pdf
  on:
    repo: studentbrad/hireme
    tags: true
