language:
- generic
compiler:
- gcc
matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends texlive-full
- sudo apt-get install ghostscript
script:
- make
deploy:
  provider: releases
  api_key:
    secure: VPKL0RyPQvJrXM+mfuAEfIFM25d2PhY9C1G2RHootK0d129XiyzmkA4XT/3dEgf8tUa8AyFUGyUt1DbyBJJme6yQ6kQq0GvNmbgX7f19E7ODKYMIgh6PU1aa5hVA7EdFb1xeyBSZ8Ygph4RL8u0R7wTde0TI68Ey4ES3VkwFDT7j/BunmrWYh7A7AHARrH6SqM/2SGVbNL9F11kHV5VCAvZ4S3RQJ5IlX64/LpIgfg1L7v9RYtHalBghZPcB9vk/fJ29Uik1E55c3rs/5Ft7vX5BcqhYKb0WQLW1bg8NkRke0IOzq4JVTtVGdCb17dY3KJvurPxVhizzJQ3wvkkOExWqK3/uquZUik6+803zE7XD6JmdX5HhC/xhnF26p+e8H6EwsKED8F+iMv8IwF22WI9FwD9mBYJYF2IlyhtnSlWX3SVIV5AyP25peULERif6RqLB1aoRE0TKbyuvMfCU1mSPFeE8pylHk37xcTjBdAAyN0LWcTSffM3y3HgFvs6fKIB/eKKeS/HN+OZ/Ih2nYvwFmeEep+AgX2ah4mG6J8y5VD8bzC0ekncl1dAz7AK4CrG1YVoYilRfdVjfzP7RmJ7tXyF7qSUZkj0PZo38sN77F7E/8d/JyzdDDI7GEbd5U8rVOcAUcRYOtCZaWygSfJ/dmNf3JUC7crUqWPXPMuA=
  file:
  - build/studentbrad_coop_contribution.pdf
  - build/studentbrad_coop_nominee_bio.pdf
  - build/studentbrad_coop_personal_statement.pdf
  - build/studentbrad_personal_bio.pdf
  - build/studentbrad_resume.pdf
  on:
    repo: studentbrad/hireme
